/* BIICODE auth bridge + community explainer — final visual. */
(function(){
  'use strict';
  function originalLogin(){const fn=window.__biicodeOriginalLogin;if(typeof fn==='function'){fn();return true}return false}
  function injectNetworkStyles(){
    if(document.getElementById('biicode-network-styles'))return;
    const s=document.createElement('style');s.id='biicode-network-styles';s.textContent=`
      .biicode-how{width:100%!important;min-height:76px!important;margin:16px 0 18px!important;padding:12px 16px!important;border:1px solid #43a6ff!important;border-radius:22px!important;background:linear-gradient(145deg,#0c2340,#071525)!important;color:#fff!important;text-align:left!important;display:flex!important;align-items:center!important;gap:13px!important;box-shadow:0 0 5px rgba(41,151,255,.9),0 0 18px rgba(21,101,255,.72),0 0 38px rgba(21,101,255,.38),inset 0 0 16px rgba(21,101,255,.12)!important;position:relative!important;overflow:hidden!important;animation:biicodeNeonPulse 2.2s ease-in-out infinite!important}
      .biicode-how:before{content:'';position:absolute;inset:0;border-radius:22px;border:1px solid rgba(255,255,255,.18);pointer-events:none}.biicode-how-icon{width:47px!important;height:47px!important;min-width:47px!important;border-radius:15px!important;background:#1565ff!important;display:grid!important;place-items:center!important;font-size:24px!important;box-shadow:0 0 12px rgba(48,157,255,.9),0 0 25px rgba(21,101,255,.55)!important}.biicode-how strong{display:block!important;font-size:18px!important;line-height:1.05!important;letter-spacing:.02em!important}.biicode-how span{display:block!important;margin-top:5px!important;color:#a9c7e8!important;font-size:11px!important;line-height:1.25!important}.biicode-how-arrow{margin-left:auto!important;font-size:31px!important;color:#55aaff!important;text-shadow:0 0 12px #1677ff!important}
      @keyframes biicodeNeonPulse{0%,100%{box-shadow:0 0 5px rgba(41,151,255,.9),0 0 18px rgba(21,101,255,.72),0 0 38px rgba(21,101,255,.38),inset 0 0 16px rgba(21,101,255,.12)}50%{box-shadow:0 0 8px rgba(72,174,255,1),0 0 26px rgba(21,101,255,.9),0 0 52px rgba(21,101,255,.48),inset 0 0 20px rgba(21,101,255,.16)}}
      .biicode-network-page{min-height:100%;padding:4px 0 34px;color:#fff}.biicode-network-top{display:flex;align-items:center;margin-bottom:6px}.biicode-network-back{border:0;background:none;color:#69adff;font-weight:900;font-size:14px;padding:8px 0;cursor:pointer}.biicode-network-logo{display:block;width:150px;max-width:62%;height:auto;margin:4px auto 14px}.biicode-network-title{font-size:31px!important;line-height:1.02!important;letter-spacing:-.045em;margin:0 0 8px!important;text-align:center}.biicode-network-title span{color:#2f8cff}.biicode-network-sub{margin:0 auto 16px;text-align:center;color:#a8b9cd;font-size:14px;line-height:1.45;max-width:400px}.biicode-comic{display:block;width:100%;height:auto;border-radius:24px;border:1px solid #315273;background:#f5f9ff;box-shadow:0 0 24px rgba(21,101,255,.13),0 16px 38px rgba(0,0,0,.24);margin:0 auto 15px}.biicode-network-message{background:linear-gradient(145deg,#12283f,#0b1726);border:1px solid #294766;border-radius:22px;padding:19px 17px;text-align:center;box-shadow:0 10px 26px rgba(0,0,0,.16)}.biicode-network-message strong{display:block;font-size:20px;line-height:1.15}.biicode-network-message p{margin:8px 0 0;color:#9eb1c6;font-size:12px;line-height:1.48}.biicode-network-cta{width:100%;min-height:53px;border:0;border-radius:16px;background:linear-gradient(135deg,#2384ff,#0758e8);color:#fff;font-weight:950;font-size:14px;margin-top:12px;box-shadow:0 0 16px rgba(21,101,255,.35)}.biicode-network-privacy{font-size:10px;color:#70849b;text-align:center;margin:12px 17px 0;line-height:1.45}
      .biicode-welcome-community{display:block;width:100%;height:auto;border-radius:24px;border:1px solid #24496f;margin:8px 0 17px;box-shadow:0 12px 32px rgba(0,0,0,.24),0 0 24px rgba(21,101,255,.12)}.biicode-welcome-community-copy{text-align:center;color:#a8b9cd;font-size:14px;line-height:1.45;margin:-5px 8px 17px}.biicode-welcome-community-copy strong{color:#fff}
      @media(max-width:380px){.biicode-how{min-height:72px!important;margin-top:14px!important;padding:11px 13px!important}.biicode-how strong{font-size:16px!important}.biicode-how span{font-size:10px!important}.biicode-how-icon{width:43px!important;height:43px!important;min-width:43px!important}.biicode-network-title{font-size:28px!important}}
    `;document.head.appendChild(s)
  }
  function openNetworkPage(){
    injectNetworkStyles();const modal=document.getElementById('modal'),mi=document.getElementById('modalin');if(!modal||!mi)return false;
    mi.innerHTML=`<div class="biicode-network-page"><div class="biicode-network-top"><button class="biicode-network-back" type="button" data-network-back>‹ INDIETRO</button></div><img class="biicode-network-logo" src="./assets/biicode-logo-v2.svg?v=network3" alt="BIICODE"><h1 class="biicode-network-title">Insieme per bici <span>più sicure.</span></h1><p class="biicode-network-sub">Una rete di ciclisti e cittadini che può aiutare a riconoscere e segnalare una bici rubata.</p><img class="biicode-comic" src="./assets/biicode-rete-comic.svg?v=final3" alt="Fumetto della rete BIICODE"><div class="biicode-network-message"><strong>La bici può essere rubata.<br>La sua identità no.</strong><p>Se qualcuno la vede, può segnalare dove l'ha trovata. Il proprietario riceve l'avviso e può attivarsi insieme alle autorità competenti.</p></div><button class="biicode-network-cta" type="button" data-network-back>TORNA ALL'APP</button><div class="biicode-network-privacy">La segnalazione non richiede i dati personali di chi avvista la bici. BIICODE non sostituisce la denuncia né le autorità competenti.</div></div>`;
    modal.classList.add('open');mi.querySelectorAll('[data-network-back]').forEach(b=>b.addEventListener('click',()=>modal.classList.remove('open')));return true
  }
  function addHowItWorks(){
    const grid=document.querySelector('.grid');if(!grid||document.querySelector('[data-biicode-how]'))return;const btn=document.createElement('button');btn.type='button';btn.className='biicode-how';btn.dataset.biicodeHow='1';btn.innerHTML='<span class="biicode-how-icon">▣</span><span><strong>COME FUNZIONA?</strong><span>Scopri la rete BIICODE in 1 minuto.</span></span><span class="biicode-how-arrow">›</span>';btn.addEventListener('click',openNetworkPage);grid.insertAdjacentElement('afterend',btn)
  }
  function simplifyWelcome(){
    const root=document.querySelector('.biicode-welcome');if(!root||root.dataset.authFix==='1')return;root.dataset.authFix='1';const inner=root.querySelector('.biicode-welcome-inner')||root;
    inner.innerHTML=`<img class="biicode-welcome-logo" src="./assets/biicode-logo-v2.svg?v=welcome21" alt="BIICODE"><img class="biicode-welcome-community" src="./assets/biicode-community.svg?v=1" alt="La community BIICODE"><div class="biicode-welcome-community-copy"><strong>Più ciclisti. Più sicurezza. Più community.</strong><br>Insieme per proteggere ciò che amiamo.</div><div class="biicode-welcome-hero"><h1>La tua bici.<br><span>La sua identità.</span></h1><p>Registrala. Identificala. Proteggila.</p></div><div class="biicode-welcome-cta"><button class="btn" type="button" data-biicode-register>REGISTRA LA MIA BICI</button><button class="biicode-welcome-secondary" type="button" data-biicode-login>HO GIÀ UN ACCOUNT · ACCEDI</button></div><div class="biicode-welcome-benefits"><article class="biicode-benefit"><div class="biicode-benefit-icon">🪪</div><div><h2>Identità</h2><p>Un codice unico per la tua bici.</p></div></article><article class="biicode-benefit"><div class="biicode-benefit-icon">🛡️</div><div><h2>Protezione</h2><p>Segnala subito un eventuale furto.</p></div></article><article class="biicode-benefit"><div class="biicode-benefit-icon">⌾</div><div><h2>Verifica</h2><p>Controlla il BIICODE tramite QR.</p></div></article></div><div class="biicode-trust">I tuoi dati personali restano protetti.</div><div class="footer-note">BIICODE · La tua bici. Un’identità unica.</div>`;
    const r=inner.querySelector('[data-biicode-register]'),l=inner.querySelector('[data-biicode-login]');if(r)r.addEventListener('click',()=>{if(typeof window.register==='function')window.register()});if(l)l.addEventListener('click',()=>{if(!originalLogin())alert('Schermata di accesso non disponibile. Ricarica la pagina.')})
  }
  function patchLoginButtons(){document.querySelectorAll('button').forEach(btn=>{const text=(btn.textContent||'').replace(/\s+/g,' ').trim().toUpperCase();if(text.includes('HO GIÀ UN ACCOUNT')||text==='ACCEDI SENZA REGISTRARTI'){btn.onclick=null;if(btn.dataset.authFixBound==='1')return;btn.dataset.authFixBound='1';btn.addEventListener('click',function(ev){ev.preventDefault();ev.stopImmediatePropagation();originalLogin()},true)}})}
  function run(){injectNetworkStyles();simplifyWelcome();addHowItWorks();patchLoginButtons()}
  const observer=new MutationObserver(()=>requestAnimationFrame(run));observer.observe(document.body,{childList:true,subtree:true});setTimeout(run,0);setTimeout(run,250);setTimeout(run,1000)
})();