/* BIICODE final welcome + auth bridge + how-it-works. */
(function(){'use strict';
function originalLogin(){const fn=window.__biicodeOriginalLogin;if(typeof fn==='function'){fn();return true}return false}
function styles(){if(document.getElementById('biicode-final-auth-styles'))return;const s=document.createElement('style');s.id='biicode-final-auth-styles';s.textContent=`
.biicode-welcome{position:fixed!important;inset:0!important;z-index:9999!important;background:#050d17!important;overflow:hidden!important;padding:0!important}
.biicode-welcome-inner{width:100%!important;max-width:540px!important;height:100dvh!important;min-height:100dvh!important;margin:0 auto!important;padding:0!important;position:relative!important;background:#050d17!important;overflow:hidden!important}
.biicode-welcome-photo{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;margin:0!important;overflow:hidden!important;border-radius:0!important;background:#102d4d!important}
.biicode-welcome-photo>img:first-child{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important;object-position:center center!important}
.biicode-welcome-logo{display:none!important}
.biicode-welcome-photo:after{content:'';position:absolute;left:0;right:0;bottom:0;height:38%;background:linear-gradient(to bottom,rgba(3,10,18,0) 0%,rgba(3,10,18,.18) 20%,rgba(3,10,18,.88) 100%);pointer-events:none}
.biicode-welcome-overlay{position:absolute!important;z-index:5!important;left:22px!important;right:22px!important;bottom:calc(22px + env(safe-area-inset-bottom))!important;text-align:center!important}
.biicode-welcome-actions{display:grid!important;gap:10px!important}
.biicode-welcome-actions button{width:100%!important;min-height:58px!important;border-radius:18px!important;font-size:15px!important;font-weight:950!important;letter-spacing:.01em!important}
.biicode-welcome-how{border:1.5px solid #55aaff!important;background:rgba(5,16,29,.82)!important;color:#fff!important;backdrop-filter:blur(10px)!important;box-shadow:0 0 16px rgba(21,101,255,.25)!important}
.biicode-welcome-register{border:0!important;background:linear-gradient(135deg,#2b83ff,#095bea)!important;color:#fff!important;box-shadow:0 10px 28px rgba(21,101,255,.42)!important}
.biicode-welcome-login{border:1.5px solid rgba(255,255,255,.65)!important;background:rgba(5,16,29,.84)!important;color:#fff!important;backdrop-filter:blur(10px)!important}
.biicode-network-page{position:relative!important;min-height:100dvh!important;padding:0!important;background:#07101b!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:auto!important}
.biicode-network-image{display:block!important;width:100%!important;height:auto!important;max-width:100%!important;max-height:none!important;object-fit:contain!important}
.biicode-network-close{position:absolute!important;z-index:2!important;top:calc(12px + env(safe-area-inset-top))!important;left:14px!important;width:38px!important;height:38px!important;border:1px solid rgba(255,255,255,.3)!important;border-radius:50%!important;background:rgba(4,12,21,.7)!important;color:#fff!important;font-size:24px!important;line-height:1!important;backdrop-filter:blur(10px)!important}
@media(max-height:760px){.biicode-welcome-overlay{bottom:calc(12px + env(safe-area-inset-bottom))!important}.biicode-welcome-actions{gap:7px!important}.biicode-welcome-actions button{min-height:50px!important;font-size:14px!important}}
`;
document.head.appendChild(s)}
function openNetworkPage(){styles();const modal=document.getElementById('modal'),mi=document.getElementById('modalin');if(!modal||!mi)return false;mi.innerHTML=`<div class="biicode-network-page"><button class="biicode-network-close" type="button" aria-label="Chiudi">×</button><img class="biicode-network-image" src="./assets/biicode-how-it-works.webp?v=13" alt="Come funziona BIICODE"></div>`;modal.classList.add('open');mi.querySelector('.biicode-network-close').addEventListener('click',()=>modal.classList.remove('open'));return true}
function simplifyWelcome(){const root=document.querySelector('.biicode-welcome');if(!root)return;const inner=root.querySelector('.biicode-welcome-inner')||root;if(inner.dataset.authFixFinal==='2')return;inner.dataset.authFixFinal='2';inner.innerHTML=`<div class="biicode-welcome-photo"><img src="./assets/biicode-welcome-final.webp?v=20260917b" alt="BIICODE community"><div class="biicode-welcome-overlay"><div class="biicode-welcome-actions"><button class="biicode-welcome-how" type="button" data-biicode-how>COME FUNZIONA?</button><button class="biicode-welcome-register" type="button" data-biicode-register>REGISTRA LA MIA BICI</button><button class="biicode-welcome-login" type="button" data-biicode-login>HO GIÀ UN ACCOUNT · ACCEDI</button></div></div></div>`;const h=inner.querySelector('[data-biicode-how]'),r=inner.querySelector('[data-biicode-register]'),l=inner.querySelector('[data-biicode-login]');if(h)h.addEventListener('click',openNetworkPage);if(r)r.addEventListener('click',()=>{if(typeof window.register==='function')window.register()});if(l)l.addEventListener('click',()=>{if(!originalLogin())alert('Schermata di accesso non disponibile. Ricarica la pagina.')})}
function patchLoginButtons(){document.querySelectorAll('button').forEach(btn=>{const text=(btn.textContent||'').replace(/\s+/g,' ').trim().toUpperCase();if(text.includes('HO GIÀ UN ACCOUNT')||text==='ACCEDI SENZA REGISTRARTI'){if(btn.dataset.authFixBound==='1')return;btn.dataset.authFixBound='1';btn.onclick=null;btn.addEventListener('click',function(ev){ev.preventDefault();ev.stopImmediatePropagation();originalLogin()},true)}})}
function run(){styles();simplifyWelcome();patchLoginButtons()}const observer=new MutationObserver(()=>requestAnimationFrame(run));observer.observe(document.body,{childList:true,subtree:true});setTimeout(run,0);setTimeout(run,250);setTimeout(run,900)})();